// Code generated by "stringer --type ConstraintType"; DO NOT EDIT.

package timetable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TeacherNotAvailable-0]
	_ = x[TeacherMinLessonsPerDay-1]
	_ = x[TeacherMaxLessonsPerDay-2]
	_ = x[TeacherMaxAfternoons-3]
	_ = x[TeacherMaxDays-4]
	_ = x[TeacherLunchBreak-5]
	_ = x[TeacherMaxGapsPerDay-6]
	_ = x[TeacherMaxGapsPerWeek-7]
	_ = x[ClassNotAvailable-8]
	_ = x[ClassMinLessonsPerDay-9]
	_ = x[ClassMaxLessonsPerDay-10]
	_ = x[ClassMaxAfternoons-11]
	_ = x[ClassLunchBreak-12]
	_ = x[ClassForceFirstHour-13]
	_ = x[ClassMaxGapsPerDay-14]
	_ = x[ClassMaxGapsPerWeek-15]
	_ = x[RoomNotAvailable-16]
	_ = x[ActivitiesEndDay-17]
	_ = x[BeforeAfterHour-18]
	_ = x[DaysBetweenJoin-19]
	_ = x[MinDaysBetween-20]
	_ = x[ParallelCourses-21]
	_ = x[MinHoursFollowing-22]
	_ = x[DoubleActivityNotOverBreaks-23]
	_ = x[LastConstraint-24]
}

const _ConstraintType_name = "TeacherNotAvailableTeacherMinLessonsPerDayTeacherMaxLessonsPerDayTeacherMaxAfternoonsTeacherMaxDaysTeacherLunchBreakTeacherMaxGapsPerDayTeacherMaxGapsPerWeekClassNotAvailableClassMinLessonsPerDayClassMaxLessonsPerDayClassMaxAfternoonsClassLunchBreakClassForceFirstHourClassMaxGapsPerDayClassMaxGapsPerWeekRoomNotAvailableActivitiesEndDayBeforeAfterHourDaysBetweenJoinMinDaysBetweenParallelCoursesMinHoursFollowingDoubleActivityNotOverBreaksLastConstraint"

var _ConstraintType_index = [...]uint16{0, 19, 42, 65, 85, 99, 116, 136, 157, 174, 195, 216, 234, 249, 268, 286, 305, 321, 337, 352, 367, 381, 396, 413, 440, 454}

func (i ConstraintType) String() string {
	if i < 0 || i >= ConstraintType(len(_ConstraintType_index)-1) {
		return "ConstraintType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstraintType_name[_ConstraintType_index[i]:_ConstraintType_index[i+1]]
}
