#!/bin/bash

#fet-cl --inputfile=input-4b.fet --writetimetableconflicts=true --writetimetablesstatistics=false --writetimetablesxml=true --writetimetablesdayshorizontal=false --writetimetablesdaysvertical=false --writetimetablestimehorizontal=false --writetimetablestimevertical=false --writetimetablessubgroups=false --writetimetablesgroups=false --writetimetablesyears=false --writetimetablesteachers=false --writetimetablesteachersfreeperiods=false --writetimetablesbuildings=false --writetimetablesrooms=false --writetimetablessubjects=false --writetimetablesactivitytags=true --writetimetablesactivities=true

# Apparently needed for ...activities.xml:
#--writetimetablesxml=true
#--writetimetablesactivitytags=true
#--writetimetablesactivities=true

fet-cl --inputfile=input-4b.fet --writetimetablesstatistics=false --writetimetablesdayshorizontal=false --writetimetablesdaysvertical=false --writetimetablestimehorizontal=false --writetimetablestimevertical=false --writetimetablessubgroups=false --writetimetablesgroups=false --writetimetablesyears=false --writetimetablesteachers=false --writetimetablesteachersfreeperiods=false --writetimetablesbuildings=false --writetimetablesrooms=false --writetimetablessubjects=false
