// Code generated by "stringer --type ConstraintType"; DO NOT EDIT.

package autotimetable

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TMinLessonsPerDay-0]
	_ = x[TMaxLessonsPerDay-1]
	_ = x[TMaxAfternoons-2]
	_ = x[TMaxDays-3]
	_ = x[TLunchBreak-4]
	_ = x[TMaxGapsPerDay-5]
	_ = x[TMaxGapsPerWeek-6]
	_ = x[CMinLessonsPerDay-7]
	_ = x[CMaxLessonsPerDay-8]
	_ = x[CMaxAfternoons-9]
	_ = x[CLunchBreak-10]
	_ = x[CForceFirstHour-11]
	_ = x[CMaxGapsPerDay-12]
	_ = x[CMaxGapsPerWeek-13]
	_ = x[LessonsEndDay-14]
	_ = x[BeforeAfterHour-15]
	_ = x[DaysBetweenJoin-16]
	_ = x[TtDaysBetween-17]
	_ = x[ParallelCourses-18]
	_ = x[MinHoursFollowing-19]
	_ = x[DoubleLessonNotOverBreaks-20]
	_ = x[LastConstraint-21]
}

const _ConstraintType_name = "TMinLessonsPerDayTMaxLessonsPerDayTMaxAfternoonsTMaxDaysTLunchBreakTMaxGapsPerDayTMaxGapsPerWeekCMinLessonsPerDayCMaxLessonsPerDayCMaxAfternoonsCLunchBreakCForceFirstHourCMaxGapsPerDayCMaxGapsPerWeekLessonsEndDayBeforeAfterHourDaysBetweenJoinTtDaysBetweenParallelCoursesMinHoursFollowingDoubleLessonNotOverBreaksLastConstraint"

var _ConstraintType_index = [...]uint16{0, 17, 34, 48, 56, 67, 81, 96, 113, 130, 144, 155, 170, 184, 199, 212, 227, 242, 255, 270, 287, 312, 326}

func (i ConstraintType) String() string {
	if i < 0 || i >= ConstraintType(len(_ConstraintType_index)-1) {
		return "ConstraintType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConstraintType_name[_ConstraintType_index[i]:_ConstraintType_index[i+1]]
}
